# Site settings
title: OMG science
email: yochannah@gmail.com
description: > #  Nerding about. Reviewing bioinformatics papers that pertain to usability
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://omgscience.co.uk" # the base hostname & protocol for your site
twitter_username: yoyehudi
github_username:  yochannah
timezone: Europe/London

# Build settings
markdown: kramdown

exclude: [vendor]

# Enable custom tag pages pls:
tag_page_layout: tag_page
tag_page_dir: tag

# Jekyll compose config
jekyll_compose:
  draft_default_front_matter:
    tags:
  post_default_front_matter:
    tags:
