# Site settings
title: OMG they do science
email: yochannah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Nerding about whilst working as a software dev. Like a sort of roadie for science.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://omgscience.co.uk" # the base hostname & protocol for your site
twitter_username: yoyehudi
github_username:  yochannah
timezone: Europe/London

# Build settings
markdown: kramdown

exclude: [vendor]

tag_page_layout: tag_page
tag_page_dir: tag
